version: "3.8"

services:
  flarum:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./flarum_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: flarum
      MYSQL_USER: flarumuser
      MYSQL_PASSWORD: flarumsecret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
